version: '2.1'
services:
  dop-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      
      LUGARES_URL: '35.203.25.118'
      LUGARES_PORT: '4005'
      LUGARES_ENTRY: 'lugares'

      USUARIOS_URL: '35.203.25.118'
      USUARIOS_PORT: '4001'
      USUARIOS_ENTRY: 'users'

      CITAS_URL: '35.203.25.118'
      CITAS_PORT: '4002'
      CITAS_ENTRY: 'citas'

      GUSTOS_URL: '35.203.25.118'
      GUSTOS_PORT: '4006'
      GUSTOS_ENTRY: ''

      EMPAREJADOR_URL: '35.203.25.118'
      EMPAREJADOR_PORT: '4004'
      EMPAREJADOR_ENTRY: 'emparejadores/'
    ports:
      - '5000:5000'
