version: '2.1'
services:
  dop-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      
      LUGARES_URL: 'lugares_ms'
      LUGARES_PORT: '4003'
      LUGARES_ENTRY: 'lugares'


      USUARIOS_URL: 'users-ms' #'35.203.25.118' 
      USUARIOS_PORT: '4001'
      USUARIOS_ENTRY: 'users'

      CITAS_URL: 'citas-ms'
      CITAS_PORT: '4005'
      CITAS_ENTRY: 'citas'

      GUSTOS_URL: 'gustos-ms'
      GUSTOS_PORT: '4002'
      GUSTOS_ENTRY: ''

      EMPAREJAMIENTO_URL: 'emparejamiento-ms'
      EMPAREJAMIENTO_PORT: '4004'
      EMPAREJAMIENTO_ENTRY: 'emparejamiento'
    ports:
      - '5000:5000'
